# Generated by Django 5.0.6 on 2024-05-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('desc', models.CharField(max_length=250, verbose_name='توضیحات')),
            ],
        ),
    ]
