# Generated by Django 5.0.6 on 2024-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_is_cms_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام کاربری'),
        ),
    ]
